# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group dependencies by their type (testing, linting, documentation, release tools)
      # to avoid overwhelming PRs and to allow for more focused updates.
      # The patterns are based on the names of the dependencies as they appear in the pyproject.toml file
      # and how they are grouped in the uv configuration.
      # Dependencies that match the patterns will be grouped together in the same PR.
       testing:
        patterns:
          - "pytest*"
          - "coverage"
          - "cryptography"
          - "deepdiff"
          - "xkcdpass"
      testing:
        patterns:
          - "pytest*"
          - "coverage"
          - "cryptography"
          - "deepdiff"
          - "xkcdpass"
      linting:
        patterns:
          - "bandit"
          - "black"
          - "codespell"
          - "mypy*"
          - "ruff"
          - "types-*"
      documentation:
        patterns:
          - "markdown*"
          - "mkdocs*"
          - "pygments*"
      release-tools:
        patterns:
          - "check-wheel-contents"
          - "twine"
          - "commitizen"
          - "prek"
