from logging import info


class BranchProtection:
    @staticmethod
    def map_config_to_protected_branch_get_data(our_branch_config: dict):
        """
        Normalizes the user-provided YAML config into the format returned by GitLab's GET endpoint.

        GitLab API Mappings:
        - 'merge_access_level' (Standard) -> 'merge_access_levels' (List)
        - 'allowed_to_merge' (Premium) -> 'merge_access_levels' (List)

        This transformation allows for a direct comparison between the desired state and current state.
        This method will normalize gitlabform branch_config to accommodate this.

        Args:
            our_branch_config (dict): branch configuration read from .yaml file

        Returns:
            dict: defined configuration transformed into the format returned by the Gitlab APIs
        """
        # Also see https://github.com/python-gitlab/python-gitlab/issues/2850

        info("Transforming *_access_level and allowed_to_* keys in Branch configuration")
        local_keys_to_gitlab_keys_map = {
            "merge_access_level": "merge_access_levels",
            "push_access_level": "push_access_levels",
            "unprotect_access_level": "unprotect_access_levels",
            "allowed_to_merge": "merge_access_levels",
            "allowed_to_push": "push_access_levels",
            "allowed_to_unprotect": "unprotect_access_levels",
        }
        new_branch_config = our_branch_config.copy()
        for key in our_branch_config:
            if key in local_keys_to_gitlab_keys_map.keys():
                target_key = local_keys_to_gitlab_keys_map[key]
                # *_access_level in gitlabform will have been transformed to it's int representation already if defined
                # by the user as "merge_access_level: Maintainer"
                if isinstance(our_branch_config[key], int):
                    access_level = new_branch_config.pop(key)
                    new_branch_config[target_key] = [
                        {
                            "id": None,
                            "access_level": access_level,
                            "user_id": None,
                            "group_id": None,
                            "deploy_key_id": None,
                        }
                    ]
                # allowed_to_* are lists...
                elif isinstance(our_branch_config[key], list):
                    mapped_list = []
                    for item in our_branch_config[key]:
                        # RAW PARAMETER PASSING: We ensure the core identity keys exist for comparison,
                        # but we preserve all other arbitrary keys provided by the user.
                        mapped_item = {
                            "id": None,
                            "access_level": item.get("access_level"),
                            "user_id": item.get("user_id"),
                            "group_id": item.get("group_id"),
                            "deploy_key_id": item.get("deploy_key_id"),
                            **{
                                k: v
                                for k, v in item.items()
                                if k not in ["access_level", "user_id", "group_id", "deploy_key_id", "id"]
                            },
                        }
                        mapped_list.append(mapped_item)
                    new_branch_config[target_key] = mapped_list
                    new_branch_config.pop(key)

        # this key is not present in
        # protected_branch.attributes, so _needs_update() would always
        # return True with this key present.
        new_branch_config.pop("protected")
        return new_branch_config

    @staticmethod
    def build_patch_request_data(
        transformed_access_levels: list[dict] | None, existing_records: tuple
    ) -> list[dict]:
        """
        Calculates the specific payload for the PATCH (update) API.

        Matching Logic:
        1. For each rule in the config, check if an identical rule already exists in GitLab.
        2. Rule Identity is determined by: user_id OR group_id OR deploy_key_id OR (role-only access_level).
        3. If a match is found, the rule is skipped (idempotency).
        4. If 'No Access' (0) is requested but other roles exist, the existing roles are marked for destruction.

        args:
            transformed_access_levels (list[dict|None]): transformed merge_access_levels or push_access_levels or unprotect_access_levels configration generated by transform_branch_config_access_levels
            existing_records (tuple): immutable list of existing records for the protected branch in Gitlab

        returns:
            list[dict]: Data in the format required by the protected_branches PATCH api. https://docs.gitlab.com/api/protected_branches/#update-a-protected-branch
        """
        patch_data = []

        if transformed_access_levels is not None:
            # User has defined in configuration some access level for this resource on the protected branch
            # Prepare patch data using raw parameters from config.
            # We only send non-None values and omit the internal 'id' placeholder used for mapping.
            for configuration in transformed_access_levels:
                item_to_add = {k: v for k, v in configuration.items() if v is not None and k != "id"}
                patch_data.append(item_to_add)

            # Check if we need to make the update (e.g. an existing record for that user_id or access_level exists)
            # and mark existing records for deletion if the access_level does not match
            # (e.g. config has changed from DEVELOPER to MAINTAINER; delete the DEVELOPER entry and add a MAINTAINER
            # entry)
            for existing_record in existing_records:
                existing_records_access_level = existing_record.get("access_level")
                existing_records_user_id = existing_record.get("user_id")
                existing_records_group_id = existing_record.get("group_id")
                existing_records_deploy_key_id = existing_record.get("deploy_key_id")

                is_match = False
                matching_item_in_patch = None

                for item in patch_data:
                    # We prioritize user_id and group_id matches over access_level.
                    # This avoids ambiguity because a user/group record from GitLab also contains an access_level.
                    # If we matched by access_level first, we might incorrectly pair a specific user's rule
                    # with a generic role-based rule from the config.
                    if existing_records_user_id is not None and item.get("user_id") == existing_records_user_id:
                        is_match = True
                    elif existing_records_group_id is not None and item.get("group_id") == existing_records_group_id:
                        is_match = True
                    elif (
                        existing_records_deploy_key_id is not None
                        and item.get("deploy_key_id") == existing_records_deploy_key_id
                    ):
                        is_match = True
                    elif (
                        item.get("user_id") is None
                        and item.get("group_id") is None
                        and item.get("deploy_key_id") is None
                    ):
                        # Role-based rule logic
                        local_level = item.get("access_level")
                        if local_level == existing_records_access_level:
                            is_match = True
                        elif local_level == 0 or existing_records_access_level == 0:
                            # "No Access" (0) is mutually exclusive with any other role.
                            # Mark existing for destruction so the new state can be applied.
                            record_id = existing_record.get("id")
                            patch_data.append({"id": record_id, "_destroy": True})
                            break

                    if is_match:
                        matching_item_in_patch = item
                        break

                if matching_item_in_patch:
                    # Rule already exists in GitLab, remove from the patch list to maintain idempotency
                    patch_data.remove(matching_item_in_patch)

                # NOTE: GitLabForm is additive. We do not destroy existing records unless they
                # conflict with a 'No Access' rule.

        else:
            info("No configuration defined for this access level. No changes will be made.")

        return patch_data

    @staticmethod
    def naive_access_level_diff_analyzer(_, cfg_in_gitlab: list, local_cfg: list):
        """
        Custom diff analyzer for branch rules.

        Following GitLabForm's ADDITIVE DESIGN, an update is needed if any rule
        defined in the local configuration is missing from GitLab.
        """
        # 1. Check if any local rule is missing from GitLab (Additive check)
        for local_item in local_cfg:
            found = False
            for gl_item in cfg_in_gitlab:
                # User Match
                if local_item.get("user_id") is not None:
                    if local_item.get("user_id") == gl_item.get("user_id"):
                        found = True
                        break
                # Group Match
                elif local_item.get("group_id") is not None:
                    if local_item.get("group_id") == gl_item.get("group_id"):
                        found = True
                        break
                # Deploy Key Match
                elif local_item.get("deploy_key_id") is not None:
                    if local_item.get("deploy_key_id") == gl_item.get("deploy_key_id"):
                        found = True
                        break
                # Role Match (Ensure GL item is also a role rule)
                if (
                    local_item.get("access_level") is not None
                    and local_item.get("access_level") == gl_item.get("access_level")
                    and gl_item.get("user_id") is None
                    and gl_item.get("group_id") is None
                    and gl_item.get("deploy_key_id") is None
                ):
                    found = True
                    break

            if not found:
                info("naive_access_level_diff_analyzer - needs_update: True (missing rule found)")
                return True

        # 2. Role exclusivity check (No Access handling)
        # Even if all local rules are "found", we need an update if GitLab has a "No Access" rule
        # while we want specific roles, or vice-versa.
        gl_role_levels = {
            r.get("access_level")
            for r in cfg_in_gitlab
            if r.get("user_id") is None and r.get("group_id") is None and r.get("deploy_key_id") is None
        }
        local_role_levels = {
            r.get("access_level")
            for r in local_cfg
            if r.get("user_id") is None and r.get("group_id") is None and r.get("deploy_key_id") is None
        }

        if (0 in gl_role_levels and any(lev > 0 for lev in local_role_levels)) or (
            0 in local_role_levels and any(lev > 0 for lev in gl_role_levels)
        ):
            info("naive_access_level_diff_analyzer - needs_update: True (No Access / Roles conflict)")
            return True

        info("naive_access_level_diff_analyzer - needs_update: False")
        return False
