name: Main branch

permissions:
  actions: read
  checks: read
  contents: read
  discussions: write
  statuses: write

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:

  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    with:
      BRANCH_REF: ${{ github.ref }}

  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      BRANCH_REF: ${{ github.ref }}

  tests-unit:
    uses: ./.github/workflows/tests-unit.yml
    with:
      BRANCH_REF: ${{ github.ref }}
    secrets: inherit

  tests-acceptance:
    uses: ./.github/workflows/tests-acceptance.yml
    with:
      BRANCH_REF: ${{ github.ref }}
    secrets: inherit
