name: Main branch

permissions:
  actions: read
  checks: read
  contents: read
  discussions: write
  statuses: write

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      BRANCH_REF: ${{ github.ref }}

  static-analysis:
    name: Lint
    uses: ./.github/workflows/static-analysis.yml
    with:
      BRANCH_REF: ${{ github.ref }}

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
    with:
      BRANCH_REF: ${{ github.ref }}
    secrets: inherit

  tests-acceptance:
    name: Acceptance Tests
    uses: ./.github/workflows/tests-acceptance.yml
    with:
      BRANCH_REF: ${{ github.ref }}
      environment: Main Tests
    secrets: inherit
