name: Main branch

permissions:
  actions: read
  checks: read
  contents: read
  discussions: write
  statuses: write

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:

  build-docs:
    uses: ./.github/workflows/docs.yml
    with:
      BRANCH_REF: ${{ github.ref }}

  linters:
    uses: ./.github/workflows/linters.yml
    with:
      BRANCH_REF: ${{ github.ref }}

  tests-acceptance:
    uses: ./.github/workflows/tests-acceptance.yml
    with:
      BRANCH_REF: ${{ github.ref }}
    secrets: inherit
