name: Docs

on:
  workflow_call:
    inputs:
      BRANCH_REF:
        type: string
        required: true

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
          fetch-depth: 2
      - name: Configure uv environment
        uses: ./.github/actions/setup-uv-local
      - name: Setup Python ${{ env.UV_PYTHON }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group docs
      - name: Build documentation
        run: |
          uv run --no-sync docs build
