name: Linters

on:
  workflow_call:
    inputs:
      BRANCH_REF:
        type: string
        required: true

jobs:
  black-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Run black
        run: |
          pip install uv==0.11.2
          uv sync --frozen --no-dev --group lint
          uv run --no-sync qa lint black --check .

  types:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.14]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run mypy
        run: |
          pip install uv==0.11.2
          uv sync --frozen --no-dev --group lint
          uv run --no-sync qa lint mypy .
