name: Linter and tests (PRs raised from Forks)

permissions:
  actions: read
  contents: read
  pull-requests: write
concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches:
      - main

jobs:
  pr_jobs:
    if: github.repository != 'gitlabform/gitlabform'
    uses: ./.github/workflows/prs.yml
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      security-events: write
    with:
      branch_ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit