name: "PR CI"

permissions:
  actions: read
  contents: read
  pull-requests: write
concurrency:
  group: ${{github.workflow}}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  pr_jobs:
    name: "Trigger"
    # github.event.pull_request object defined here: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2026-03-10#get-a-pull-request
    if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'gitlabform/gitlabform') || (github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != 'gitlabform/gitlabform') }}
    uses: ./.github/workflows/pr-ci-workflow.yml
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      security-events: write
    with:
      BRANCH_REF: ${{ github.event.pull_request.head.sha }}
    secrets: inherit