name: "CI - PRs"

permissions:
  actions: read
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  pr_jobs:
    name: "Pipeline"
    uses: ./.github/workflows/pr-ci-workflow.yml
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    with:
      BRANCH_REF: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
