name: "CI - Acceptance Tests"

permissions:
  actions: read
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches:
      - main

jobs:
  tests-acceptance:
    name: "Acceptance Tests"
    uses: ./.github/workflows/tests-acceptance.yml
    permissions:
      actions: read
      contents: read
      packages: read
    with:
      BRANCH_REF: ${{ github.event.pull_request.head.sha }}
      environment: Integrate Pull Request
    secrets: inherit
