name: Tests standard

on:
  workflow_call:
    inputs:
      BRANCH_REF:
        type: string
        required: true

permissions:
  contents: read

jobs:

  acceptance-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.14]
      fail-fast : false
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
          fetch-depth: 2
      - name: Configure uv environment
        uses: ./.github/actions/setup-uv-local
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group test
      - name: Start GitLab in Docker
        run: |
          uv run --no-sync gitlab-local up
      - name: Run standard acceptance tests against Enterprise Edition
        run: uv run --no-sync qa test tests/acceptance/standard --cov=. --cov-report=xml --durations=0 --reruns 3 --reruns-delay 10 --log-cli-level=WARNING
      - name: Upload coverage to Codecov
        uses: Wandalen/wretry.action@v3
        with:
          action: codecov/codecov-action@v3
          with: |
            name: codecov-acceptance-test-standard
            flags: integration
            fail_ci_if_error: true
            token: 3e6d6cb5-fcdb-41ea-b134-f6c5856363e9
          attempt_limit: 5
          attempt_delay: 10000

  acceptance-tests-CE:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [ 3.14 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
          fetch-depth: 2
      - name: Configure uv environment
        uses: ./.github/actions/setup-uv-local
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group test
      - name: Start GitLab in Docker
        run: |
          uv run --no-sync gitlab-local up --gitlab-flavor ce
      - name: Run standard acceptance tests against Community Edition
        run: uv run --no-sync qa test tests/acceptance/standard --cov=. --cov-report=xml --durations=0 --reruns 3 --reruns-delay 10 --log-cli-level=WARNING
      - name: Upload coverage to Codecov
        uses: Wandalen/wretry.action@v3
        with:
          action: codecov/codecov-action@v3
          with: |
            name: codecov-acceptance-test-standard-ce
            flags: integration
            fail_ci_if_error: true
            token: 3e6d6cb5-fcdb-41ea-b134-f6c5856363e9
          attempt_limit: 5
          attempt_delay: 10000

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.14, 3.12]
      fail-fast : false
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
          fetch-depth: 2
      - name: Configure uv environment
        uses: ./.github/actions/setup-uv-local
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group test
      - name: Run unit tests
        run: |
          uv run --no-sync qa test tests/unit --cov=. --cov-report=xml --log-cli-level=WARNING
      - name: Upload coverage to Codecov
        uses: Wandalen/wretry.action@v3
        with:
          action: codecov/codecov-action@v3
          with: |
            flags: unittests
            fail_ci_if_error: true
            token: 3e6d6cb5-fcdb-41ea-b134-f6c5856363e9
          attempt_limit: 5
          attempt_delay: 10000

  security-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [ 3.14, 3.12 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
          fetch-depth: 2
      - name: Configure uv environment
        uses: ./.github/actions/setup-uv-local
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group test
      - name: Run security tests
        run: |
          uv run --no-sync qa lint bandit gitlabform

  smoke-tests:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ 3.14, 3.12 ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
          fetch-depth: 2
      - name: Configure uv environment
        uses: ./.github/actions/setup-uv-local
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group test
      - name: Run smoke tests
        run: |
          uv run --no-sync gitlabform -V
