name: Tests premium

on:
  workflow_call:
    inputs:
      BRANCH_REF:
        type: string
        required: true
      environment:
        description: "Environment to run tests in: 'Integrate Pull Request' for PRs (requires approval) or 'Main' for Main."
        type: string
        required: true

jobs:
  acceptance-tests-premium:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.14]
      fail-fast : false
    env:
      UV_PYTHON: ${{ matrix.python-version }}
      UV_VERSION: 0.11.7
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Setup Python ${{ matrix.python-version }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group test
      - name: Start GitLab in Docker
        env:
          GITLAB_EE_LICENSE: ${{ secrets.GITLAB_EE_LICENSE }}
        run: |
          uv run --no-sync gitlab-local up
      - name: Run acceptance tests for premium features
        run: |
          uv run --no-sync qa test tests/acceptance/premium --cov=. --cov-report=xml --durations=0 --reruns 3 --reruns-delay 10 --log-cli-level=WARNING
      - name: Upload coverage to Codecov
        uses: Wandalen/wretry.action@v3
        with:
          action: codecov/codecov-action@v3
          with: |
            name: codecov-acceptance-test-premium
            flags: integration
            fail_ci_if_error: true
            token: 3e6d6cb5-fcdb-41ea-b134-f6c5856363e9
          attempt_limit: 5
          attempt_delay: 10000
