name: Tests standard

on:
  workflow_call:
    inputs:
      BRANCH_REF:
        type: string
        required: true

permissions:
  contents: read

jobs:
  smoke-tests:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ 3.14, 3.12 ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.BRANCH_REF }}
          fetch-depth: 2
      - name: Configure uv environment
        uses: ./.github/actions/setup-uv-local
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }} and install dependencies
        run: |
          uv sync --frozen --no-dev --group test
      - name: Run smoke tests
        run: |
          uv run --no-sync gitlabform -V
